name: example
publish_to: "none"

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  calendar_view_utils:

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  calendar_view_utils:
    path: ../

flutter:
  uses-material-design: true
