name: calendar_view_utils
description: Core classes/utilities useful for building custom calendar views.
version: 1.0.2
homepage: https://github.com/justinlettau/calendar_view_utils

environment:
  sdk: "<4.0.0"

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0
