name: calendar_view_utils
description: Utilities for building calendar views.
version: 1.0.0
homepage: https://github.com/justinlettau/calendar_view_utils

environment:
  sdk: ">=2.17.5 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
